---
- hosts: nagios
  become: yes
  remote_user: ubuntu
  gather_facts: yes
 

  tasks:
   - name: updating the system
     command: sudo apt-get update -y

   - name: installing python
     package:
      name: python
      state: present
   
   - name: installing nagios server
     package:
      name: nagios3
      state: present

   - name: installing passlib python
     package:
      name: python-passlib
      state: present

   - htpasswd:
      path: /etc/nagios3/htpasswd.users
      name: nagiosadmin
      password: nagiosadmin
      owner: root

#   - name: Copying nagios host to server
#     command: scp /home/ubuntu/playbooks/ansible/google.cfg 54.68.8.24:/etc/nagios3/conf.d

   - name: restarting nagios service
     command:
      name: nagios3
      state: restarted
