---
- hosts: nagios
  become: yes
  remote_user: ubuntu
  gather_facts: yes
 

  tasks:
   - name: updateing cache
     apt:
      update_cache: yes
 
   - name: installing python
     package:
      name: python
      state: present
   
   - name: installing nagios server
     package:
      name: nagios3
      state: present

   - name: installing passlib python
     package:
      name: python-passlib
      state: present

   - htpasswd:
      path: /etc/nagios3/htpasswd.users
      name: nagiosadmin
      password: nagiosadmin
      owner: root

   - name: Copying file to nagios
     copy:
      src: /home/ubuntu/playbooks/ansible/google.cfg
      dest: /etc/nagios3/conf.d/google.cfg

#   - name: Copying nagios host to server
#     command: scp /home/ubuntu/playbooks/ansible/google.cfg 52.36.99.110:/etc/nagios3/conf.d

   - name: restarting nagios service
     service:
      name: nagios3
      state: restarted
