---
- hosts: nagios
  become: yes
  remote_user: ubuntu
  gather_facts: yes
 
  tasks:
   - name: installing nagios server
     package:
      name: nagios3
      state: present

  tasks:
   - name: installing passlib python
     package:
      name: python-passlib
      state: present

   - htpasswd:
      path: /etc/nagios3/htpasswd.users
      name: nagiosadmin
      password: nagiosadmin
      owner: root
