---
- name: update apt cache
  apt:
   update_cache: yes
  when:
   - ansible_os_family == "Debian"

- name: installing required packages
  package: 
   name: "{{ item }}"
   state: present
  with_items:
   - python
   - nagios3
